# Generated by Django 5.0.7 on 2025-01-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leetcodeproblem',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
