# Generated by Django 5.0.7 on 2025-01-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeApp', '0002_leetcodeproblem_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leetcodeproblem',
            name='done',
        ),
    ]
